// config/GameConstants.js - Очищенная версия с убранными дублями
export const GAME_CONSTANTS = {
  // Timing constants
  NOTIFICATION_DURATION: 3000,
  SKILL_NOTIFICATION_DURATION: 4000,
  SAVE_ELEMENT_TIMEOUT: 10000,
  RELOAD_DELAY: 2000,
  
  // Effect constants
  FRENZY_MULTIPLIER: 2,
  DOUBLE_TAP_MULTIPLIER: 2,
  SPEED_BOOST_MULTIPLIER: 0.5,
  RAPID_SPEED_MULTIPLIER: 5,
  LUCKY_BUFF_BONUS: 25,
  GHOST_CLICK_CHANCE: 0.5,
  SLOT_MACHINE_CHANCE: 0.3,
  SLOT_MACHINE_AMOUNT: 3,
  STAR_POWER_CLICKS: 5,
  STAR_POWER_BONUS: 5,
  SHIELD_BLOCKS: 3,
  HEAVY_CLICK_REQUIRED: 2,
  TAX_COLLECTOR_PERCENT: 0.05,
  TAX_COLLECTOR_INTERVAL: 3000,
  EXPLOSION_DAMAGE_PERCENT: 0.1,
  WATERFALL_INTERVAL: 900,
  WATERFALL_AMOUNT: 1,

  // Энергетические константы
  INITIAL_ENERGY: 100,              // Начальная энергия
  INITIAL_MAX_ENERGY: 100,          // Начальная максимальная энергия
  BASE_REGEN_RATE: 1,               // Базовая скорость регенерации
  REGEN_INTERVAL: 15000,            // Интервал регенерации (15 сек)
  CLICK_COST: 1,                    // Стоимость клика
  ZONE_RESTORE: 1,
  GOLD_ZONE_RESTORE: 4,
  WARNING_THRESHOLD: 20,
  CRITICAL_THRESHOLD: 10,
  PULSE_THRESHOLD: 10,
  GENERATOR_REGEN_BONUS: 0.5,
  GENERATOR_MAX_ENERGY_BONUS: 10,
  MASTERY_REGEN_BONUS: 1.0,
  STORAGE_MAX_BONUS: 50,
  EFFICIENCY_REDUCTION: 0.25,
  ENERGY_PACK_RESTORE: 50,
  
  // Market constants
  BASIC_RESOURCE_PRICE: 2000,
  ENERGY_PACK_PRICE: 5000,
  SCIENCE_BOOK_PRICE: 8000,
  FAITH_RELIC_PRICE: 10000,
  CHAOS_NEUTRALIZER_PRICE: 15000,
  SKILL_CRYSTAL_PRICE: 20000,
  
  // Auto clicker constants
  AUTO_CLICKER_BASE_INTERVAL: 10000,
  AUTO_CLICKER_MIN_INTERVAL: 1000,
  
  // Achievement constants
  COMBO_CHECK_INTERVAL: 10000,
  RESOURCE_CHECK_INTERVAL: 30000,
  COMBO_MILESTONE_1: 10,
  COMBO_MILESTONE_2: 25,
  COMBO_MILESTONE_3: 50,
  RESOURCE_MILESTONE_1: 1000,
  RESOURCE_MILESTONE_2: 5000,
  RESOURCE_MILESTONE_3: 10000,
  
  // UI constants
  TOOLTIP_OFFSET: 10,
  
  // Validation constants
  MAX_SAFE_RESOURCE_VALUE: Number.MAX_SAFE_INTEGER,
  MIN_RESOURCE_VALUE: 0,
  MAX_COMBO_COUNT: 999999,
  MAX_SKILL_POINTS: 999999,
  
  // Game mechanics
  COMBO_TIMEOUT: 5000,
  MAX_COMBO_MULTIPLIER: 10,
  ZONE_SHUFFLE_CHANCE: 75,
  BASE_EFFECT_CHANCE: 10,
  EFFECT_CHANCE_RANGE: { min: 5, max: 25 }
};

export const UI_CONFIG = {
  CANVAS_SIZE: 500,
  ROTATION_SPEED: 0.005,
  BLOCK_DURATION: 3000
};

export const UI_COLORS = {
  RARITY_COMMON: '#9E9E9E',
  RARITY_UNCOMMON: '#4CAF50', 
  RARITY_RARE: '#FF9800',
  RARITY_EPIC: '#9C27B0',
  
  SEVERITY_MILD: '#FF9800',
  SEVERITY_MODERATE: '#f44336',
  SEVERITY_SEVERE: '#8E24AA',
  
  SUCCESS: '#4CAF50',
  WARNING: '#FF9800',
  ERROR: '#f44336',
  INFO: '#2196F3'
};